### ISSUE TITLE
ConsoleAppender$SystemOutStream should never close FileDescriptor.out

### ISSUE THREAD

**Issue by tobiasct** [jboss-logging/log4j-jboss-logmanager#22]
Hello,
we had an issue with log4j configuration and "stdout not working any more".

Problems:
- you deliver a specific log4j implementation
- which - in contrast to the original one - closes System.out aka FileDescriptor.out

Original Log4j does nothing inside close() but your implementation closes FileDescriptor.out which leads to "System.out not working any more" as FileDescriptor.valid() returns false then.

public SystemOutStream() {
     out = createPrintStream(FileDescriptor.out);
}

public void close() {
            out.close();    <<<<< this is terribly wrong
}

**Comment by jamezp** [comment]
Please let me apologize for just now seeing this. I've somehow never looked at the issues here. And yes this is VERY wrong as you say. I'll get this fixed ASAP.
