### ISSUE TITLE
LoggingEvent can't manage Object Message

### ISSUE THREAD

**Issue by ede94** [jboss-logging/log4j-jboss-logmanager#8]
Hello,

I'm trying to pass personalized object message throught LoggingEvent and access it in personalized appender.
This works with standard Log4j implementation.
With log4j-jboss-logmanager implementation, LoggingEvent's constructor transforms message parameter from Object to String calling message.toString().
Is it possible to preserve and manage Object type of message parameter in LoggingEvent object ?

Thanks.

**Comment by jamezp** [comment]
Wow, I'm only  7 years late on this. I truly apologize. I'm not sure how I haven't looked here in that long. Anyway, this is because JBoss Log Manager expects a string for the message and the `LoggingEvent`. If this is still, 7 years later :facepalm:, an issue please feel free to reopen this.
